In [1]:
import numpy as np
from algorithms import *
# set goal state
goal_state = [[1,2,3], [8,0,4], [7,6,5]]    # 0 for 'empty'
goal_state = State(goal_state)
print(goal_state)

[1 2 3]
[8 0 4]
[7 6 5]



In [2]:
# random start state
import numpy as np
start_state = np.arange(9)
np.random.shuffle(start_state)
start_state = State(start_state.reshape(3,3))
print(start_state)

[0 2 5]
[3 6 1]
[8 7 4]



In [3]:
bfs(State([[1,2,3],[8,4,5],[7,0,6]]), goal_state)

Found path in 19 steps


[[1 2 3]
 [8 4 5]
 [7 0 6],
 [1 2 3]
 [8 4 5]
 [7 6 0],
 [1 2 3]
 [8 4 0]
 [7 6 5],
 [1 2 3]
 [8 0 4]
 [7 6 5]]

In [4]:
ucs(State([[1,2,3],[8,4,5],[7,0,6]]), goal_state)

Found path in 19 steps


[[1 2 3]
 [8 4 5]
 [7 0 6],
 [1 2 3]
 [8 4 5]
 [7 6 0],
 [1 2 3]
 [8 4 0]
 [7 6 5],
 [1 2 3]
 [8 0 4]
 [7 6 5]]

In [5]:
heuristic_available = ["Hamming", "Manhatten", "Permutation Inversion", "non-admissible"]
astar(State([[1,2,3],[8,4,5],[7,0,6]]), goal_state, heuristic_available[0])

Found path in 5 steps


[[1 2 3]
 [8 4 5]
 [7 0 6],
 [1 2 3]
 [8 4 5]
 [7 6 0],
 [1 2 3]
 [8 4 0]
 [7 6 5],
 [1 2 3]
 [8 0 4]
 [7 6 5]]

In [6]:
astar(State([[1,2,3],[8,4,5],[7,0,6]]), goal_state, heuristic_available[1])

Found path in 19 steps


[[1 2 3]
 [8 4 5]
 [7 0 6],
 [1 2 3]
 [8 4 5]
 [7 6 0],
 [1 2 3]
 [8 4 0]
 [7 6 5],
 [1 2 3]
 [8 0 4]
 [7 6 5]]

In [7]:
astar(State([[1,2,3],[8,4,5],[7,0,6]]), goal_state, heuristic_available[2])

Found path in 6 steps


[[1 2 3]
 [8 4 5]
 [7 0 6],
 [1 2 3]
 [8 4 5]
 [7 6 0],
 [1 2 3]
 [8 4 0]
 [7 6 5],
 [1 2 3]
 [8 0 4]
 [7 6 5]]

In [6]:
astar(State([[1,2,3],[8,4,5],[7,0,6]]), goal_state, heuristic_available[3])

NameError: name 'astar' is not defined

从上面non-admissible的结果来看，483steps，明显不是最优的。

In [9]:
from itertools import combinations
for i, j in combinations(goal_state.array.reshape(9), 2):
    print(i, j)

1 2
1 3
1 8
1 0
1 4
1 7
1 6
1 5
2 3
2 8
2 0
2 4
2 7
2 6
2 5
3 8
3 0
3 4
3 7
3 6
3 5
8 0
8 4
8 7
8 6
8 5
0 4
0 7
0 6
0 5
4 7
4 6
4 5
7 6
7 5
6 5
